version: '2'
services:
  mysql:
    image: mysql:5.6
    container_name: "appetcaredb"
    hostname: "appetcaredb"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "appetcare"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    hostname: "phpmyadmin"
    ports:
      - 8080:80
    volumes:
      - phpmyadmin_data:/sessions
    environment:
      PMA_HOST: "appetcaredb"
      PMA_USER: "root"
      PMA_PASSWORD: "secret"
    restart: always
    links:
      - "mysql"
  app:
    restart: always
    image: php:7
    command: php -S 0.0.0.0:8000 /app/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
    - .:/app 
volumes:
  mysql_data:
  phpmyadmin_data:
  app:
